service: aws-lambda
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs18.x
  region: sa-east-1

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /checkPapers
          method: post
